### ISSUE TITLE
[Bug]: type imports not working in v2

### ISSUE THREAD

**Issue by OrmEmbaar** [helius-labs/helius-sdk#214]
### SDK Version

2.0.0

### Environment

Node 22

### Describe the Bug

The types imports appear to be broken for v2. `createHelius` should returned a defined HeliusClient type. However, the returned value has a type of `any`. When inspecting the installed package in `node_modules`, it seems the old v1 types are still present and that package.json `types` field is pointing at those types. 

<img width="932" height="457" alt="Image" src="https://github.com/user-attachments/assets/5ffbcb98-a87c-4a3c-b174-c6c4cb42fe3e" />

<img width="1728" height="1078" alt="Image" src="https://github.com/user-attachments/assets/f3c1d748-d191-478c-9cb9-315b217cce4c" />

### Steps to Reproduce

```typescript
import { createHelius, type HeliusClient } from 'helius-sdk'

const helius = createHelius({ apiKey: process.env.HELIUS_API_KEY! });

helius.hahaThisIsNotAMethod('foooo'); // builds without error
```

### Expected Behavior

The package types should work properly with typescript. 

### Logs/Screenshots

```shell

```

### Additional Checks

- [x] I have searched for existing issues and this is not a duplicate.
- [x] I have tested with the latest version.

**Comment by OrmEmbaar** [comment]
@0xIchigo The fix is also broken; it's now not possible to import the package at all. Looks to me like the issue is broken import paths. The package.json references `./dist/src/rpc/index.js`, but I think it should be `./dist/rpc/index.js` (there is no `src` directory in the build dir).

**Comment by 0xIchigo** [comment]
Damn, that's my b @OrmEmbaar—forgot to push the other commit since it's flattened. Cutting a new release now. Thanks!

**Comment by 0xIchigo** [comment]
@OrmEmbaar, thank you again for your help! Everything is now fixed in version 2.0.2 🥳

**Comment by OrmEmbaar** [comment]
Sorry @0xIchigo but this still isn't working. Intellisense gives me `type HeliusClient = any` when I hover `HeliusClient` in `dist/index.d.ts`. I think `ResolvedHeliusRpcApi` is resolving to `any`, forcing the `HeliusClient` intersection type to `any`.

**Comment by 0xIchigo** [comment]
Ah. I took another look @OrmEmbaar, and it seems that `ResolvedHeliusRpcApi` gets resolved to `any` in intellisense instead of its current type, causing the entire intersection to degrade to `any`. Will open another PR for this so it's fixed in the next release
